spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:54320/postgres"
    username: user
    password: pass

#    spring:
#      mvc:
#        static-path-pattern=/uploads/**: